sudo: required
# blocklist 
branches: 
except: 
- legacy 
- experimental 
# safelist 
branches: 
only: 
- master 
- stable
- test


services:
  - docker

language: python

python:
  - '2.7'

script: nosetests

deploy:
all_branches: true
  on:
    branch:master
