sudo: required
# blocklist 
branches: 
except: 
- legacy 
- experimental 
# safelist 
branches: 
only: 
- master 
- stable

services:
  - docker

language: python

python:
  - '2.7'

script: nosetests

deploy:

  on:
    branch:master
