
sudo: required #is required to use docker service in travis

language: php #can be any language, just php for example

services:
  - docker # required, but travis uses older version of docker :(

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
- echo "no tests!" # put your normal testing scripts here

